In [2]:
import pandas as pd
import altair as alt
import plotly.graph_objects as go
import numpy as np

In [3]:
industry_df = pd.read_csv('Industry_Carbon_Emission.csv')
sea_df = pd.read_csv('Sea_Levels.csv')

In [4]:
print(industry_df.columns)
print('-'*100)
print(sea_df.columns)

Index(['ObjectId', 'Country', 'ISO2', 'ISO3', 'Indicator', 'Unit', 'Source',
       'CTS Code', 'CTS Name', 'CTS Full Descriptor', 'Industry', 'Scale',
       '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003',
       '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012',
       '2013', '2014', '2015', '2016', '2017', '2018'],
      dtype='object')
----------------------------------------------------------------------------------------------------
Index(['ObjectId', 'Country', 'ISO2', 'ISO3', 'Indicator', 'Unit', 'Source',
       'CTS Code', 'CTS Name', 'CTS Full Descriptor', 'Measure', 'Date',
       'Value'],
      dtype='object')

In [5]:
sea_df.head()

,ObjectId,Country,ISO2,ISO3,Indicator,Unit,Source,CTS Code,CTS Name,CTS Full Descriptor,Measure,Date,Value
0,1,World,NaN,WLD,Change in mean sea level: Sea level: TOPEX.Pos...,Millimeters,National Oceanic and Atmospheric Administratio...,ECCL,Change in Mean Sea Level,"Environment, Climate Change, Climate and Weath...",Arabian Sea,D10/17/1992,-62.50
1,2,World,NaN,WLD,Change in mean sea level: Sea level: TOPEX.Pos...,Millimeters,National Oceanic and Atmospheric Administratio...,ECCL,Change in Mean Sea Level,"Environment, Climate Change, Climate and Weath...",Atlantic Ocean,D10/17/1992,2.91
2,3,World,NaN,WLD,Change in mean sea level: Sea level: TOPEX.Pos...,Millimeters,National Oceanic and Atmospheric Administratio...,ECCL,Change in Mean Sea Level,"Environment, Climate Change, Climate and Weath...",Bay Bengal,D10/17/1992,10.31
3,4,World,NaN,WLD,Change in mean sea level: Sea level: TOPEX.Pos...,Millimeters,National Oceanic and Atmospheric Administratio...,ECCL,Change in Mean Sea Level,"Environment, Climate Change, Climate and Weath...",Bering Sea,D10/17/1992,33.85
4,5,World,NaN,WLD,Change in mean sea level: Sea level: TOPEX.Pos...,Millimeters,National Oceanic and Atmospheric Administratio...,ECCL,Change in Mean Sea Level,"Environment, Climate Change, Climate and Weath...",Caribbean Sea,D10/17/1992,75.12

In [6]:
industry_df['Industry']

0                          Accomodation and food services
1       Activities of households as employers; undiffe...
2                     Administrative and support services
3                          Agriculture, hunting, forestry
4                                           Air transport
                              ...
8905    Warehousing and support activities for transpo...
8906    Water supply; sewerage, waste management and r...
8907                                      Water transport
8908    Wholesale and retail trade; repair of motor ve...
8909                   Wood and products of wood and cork
Name: Industry, Length: 8910, dtype: object

**Proposition: Increase in use of water transport in global trade increases net carbon emissions, resulting in higher sea levels.**

In [7]:
# Columns to keep
year_columns = [str(year) for year in range(1995, 2019)]
useful_columns = ['Country', 'Industry', 'Unit'] + year_columns

# Filter and subset
water_transport_df = industry_df[
    (industry_df['Industry'] == 'Water transport')
][useful_columns]
water_transport_df

,Country,Industry,Unit,1995,1996,1997,1998,1999,2000,2001,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
42,Argentina,Water transport,Millions of Metric tons of CO2,1.296000,1.513000,1.762000,2.007000,1.770000,1.386000,1.546000,...,1.358000,2.262000,2.593000,2.653000,2.793000,2.787000,2.648000,2.255000,2.074000,1.941000
87,Argentina,Water transport,Metric Tons of CO2 Emissions per $1million USD...,2292.182526,2527.564317,2733.478126,2499.377335,2358.427715,1840.637450,2164.659759,...,1745.276957,2282.312582,2140.675308,2055.792329,1973.572640,2063.221794,1841.958820,1795.096322,1383.404482,1497.223079
132,Argentina,Water transport,Metric Tons of CO2 Emissions per $1million USD...,2386.352348,2624.530738,2832.521921,2598.362676,2473.057146,1974.862086,2295.658235,...,1929.477343,2443.206028,2271.684821,2175.061845,2090.771534,2195.890742,1966.661016,1931.940152,1498.558535,1625.332774
177,Australia,Water transport,Millions of Metric tons of CO2,5.327000,5.524000,6.341000,5.314000,6.355000,6.738000,6.305000,...,12.034000,10.937000,9.804000,10.558000,10.275000,9.252000,9.381000,10.434000,10.046000,9.684000
222,Australia,Water transport,Metric Tons of CO2 Emissions per $1million USD...,787.924506,752.855235,821.766909,750.511969,936.362699,958.750124,968.301748,...,791.898081,636.916340,480.225712,446.778439,454.976177,411.428571,485.483621,580.385700,532.831229,461.972207
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8727,United States,Water transport,Metric Tons of CO2 Emissions per $1million USD...,2264.851221,2039.141064,1888.191191,1775.042732,1790.510459,1895.963448,1539.185445,...,1056.236919,1083.296113,1670.605837,1450.295057,1444.581889,1339.743768,1346.987771,1317.347962,1289.437422,983.714388
8772,United States,Water transport,Metric Tons of CO2 Emissions per $1million USD...,3278.949539,3022.443054,2898.023304,2576.212418,2348.840494,2559.260154,1867.318754,...,1194.803244,1229.431307,1827.654645,1610.597072,1590.542077,1480.845883,1474.590577,1445.167246,1411.519108,1097.475222
8817,Vietnam,Water transport,Millions of Metric tons of CO2,0.856000,1.036000,1.017000,1.419000,1.286000,1.192000,2.755000,...,4.958000,4.428000,3.733000,3.633000,4.013000,5.135000,8.340000,13.168000,13.132000,12.848000
8862,Vietnam,Water transport,Metric Tons of CO2 Emissions per $1million USD...,4514.767932,4174.053183,3820.435763,4813.432836,4734.904271,4130.284130,6432.407191,...,3397.985059,2768.019004,2023.744985,1667.890919,1681.612471,1862.937164,2727.272727,3771.877059,3492.460307,3124.513619
8907,Vietnam,Water transport,Metric Tons of CO2 Emissions per $1million USD...,4962.411721,4524.064409,4186.056061,5198.122248,5090.530714,4466.546521,7091.604979,...,3807.684853,3020.134010,2253.246177,1917.872096,1908.984147,2093.765490,2982.160528,3974.738515,3664.875652,3295.556416

In [8]:
# Step 1: Rename columns to avoid confusion (optional but helpful)
sea_level_df = sea_df.rename(columns={'Measure': 'Location'})

# Step 2: Keep only relevant columns
sea_level_df = sea_level_df[['Date', 'Location', 'Value', 'Unit']].copy()

# Step 3: Convert Date to datetime
sea_level_df['Date'] = pd.to_datetime(sea_level_df['Date'].str.replace('D', ''))
sea_level_df.sort_values(['Location'])

            Date      Location  Value         Unit
36892 2022-07-02  Adriatic Sea  66.80  Millimeters
38994 2023-08-22  Adriatic Sea  78.73  Millimeters
38995 2023-08-23  Adriatic Sea  74.10  Millimeters
20700 2010-07-15  Adriatic Sea  15.97  Millimeters
20680 2010-07-11  Adriatic Sea  16.14  Millimeters
...          ...           ...    ...          ...
18603 2009-05-21    Yellow Sea -34.07  Millimeters
18578 2009-05-16    Yellow Sea -69.02  Millimeters
18552 2009-05-11    Yellow Sea -23.17  Millimeters
18703 2009-06-10    Yellow Sea  21.73  Millimeters
41692 2025-02-18    Yellow Sea   3.33  Millimeters

[41693 rows x 4 columns]

In [9]:
water_transport_df['Unit'].unique()

array(['Millions of Metric tons of CO2',
       'Metric Tons of CO2 Emissions per $1million USD of output'],
      dtype=object)

In [10]:
water_transport_df = water_transport_df.groupby('Unit').sum().iloc[:,2:]

In [11]:
# Plot emission (ppm) due to water transport per year
emission_df = water_transport_df.iloc[1:]

emission_df = emission_df.melt(
    var_name='Year',
    value_name='emission'
)
emission_df['Year'] = emission_df['Year'].astype(int)
alt.Chart(emission_df).mark_line(point=True).encode(
    x=alt.X('Year:O', title='Year', axis=alt.Axis(labelAngle=0)),
    y=alt.Y('emission:Q',
            title='CO₂ Emission (PPM)',
            scale=alt.Scale(domain=[490, 900])),
    tooltip=['Year', 'emission']
).properties(
    title='Water Transport CO₂ Emissions (1995–2018)',
    width=600,
    height=400
).interactive()

alt.Chart(...)

In [12]:
sea_level_df['Year'] = pd.to_datetime(sea_level_df['Date']).dt.year
yearly_sea_levels = sea_level_df.groupby('Year', as_index=False)['Value'].mean()
yearly_sea_levels = yearly_sea_levels[(yearly_sea_levels['Year']>=1995) & (yearly_sea_levels['Year']<=2018)]
yearly_sea_levels.columns = ['Year', 'AvgSeaLevel']

In [13]:
alt.Chart(yearly_sea_levels).mark_line(point=True).encode(
    x=alt.X('Year:O', title='Year'),
    y=alt.Y('AvgSeaLevel:Q', title='Average Sea Level (mm)'),
    tooltip=['Year', 'AvgSeaLevel']
).properties(
    title='Average Global Sea Level Change by Year',
    width=600,
    height=400
).interactive()

alt.Chart(...)

In [14]:
# Make sure data is sorted
emission_df = emission_df.sort_values('Year')
yearly_sea_levels = yearly_sea_levels.sort_values('Year')

# Apply 3-year centered rolling average
emission_df['emission_smoothed'] = emission_df['emission'].rolling(window=3, center=True).mean()
yearly_sea_levels['AvgSeaLevel_smoothed'] = yearly_sea_levels['AvgSeaLevel'].rolling(window=3, center=True).mean()

In [15]:
# --- CO2 Emissions Trace (left Y-axis) ---
emission_trace = go.Scatter(
    x=emission_df['Year'],
    y=emission_df['emission'],
    name='CO₂ Emissions (PPM)',
    yaxis='y1',
    mode='lines+markers',
    line=dict(color='green')
)

# --- Sea Level Trace (right Y-axis) ---
sea_level_trace = go.Scatter(
    x=yearly_sea_levels['Year'],
    y=yearly_sea_levels['AvgSeaLevel'],
    name='Sea Level (mm)',
    yaxis='y2',
    mode='lines+markers',
    line=dict(color='blue')
)

# --- Combine the Traces ---
fig = go.Figure(data=[emission_trace, sea_level_trace])

fig.update_layout(
    title='Water Transport CO₂ Emissions vs Sea Level Rise (1995–2018)',
    xaxis=dict(title='Year'),

    yaxis=dict(
        title=dict(text='CO₂ Emissions (PPM)', font=dict(color='green')),
        range=[490, 900],
        tickfont=dict(color='green')
    ),

    yaxis2=dict(
        title=dict(text='Average Sea Level (mm)', font=dict(color='blue')),
        overlaying='y',
        side='right',
        tickfont=dict(color='blue')
    ),

    legend=dict(x=0.5, y = -0.2, xanchor='center', orientation='h')
)


fig.show()

In [16]:
year_cols = [str(y) for y in range(1995, 2019)]

# Total emissions across all industries
total = industry_df[year_cols].sum()

# Water transport emissions
water = industry_df[industry_df['Industry'] == 'Water transport'][year_cols].iloc[0]

# Compute proportion (%)
proportion_df = pd.DataFrame({
    'Year': [int(y) for y in year_cols],
    'Proportion': (water / total) * 100
})
proportion_df['RelativeGrowth'] = (proportion_df['Proportion'] / proportion_df['Proportion'].iloc[0]) * 100

In [17]:
import plotly.graph_objects as go

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=proportion_df['Year'],
    y=proportion_df['RelativeGrowth'],
    mode='lines+markers',
    name='Relative Growth',
    line=dict(color='green'),
    marker=dict(size=6),
    hovertemplate='Year: %{x}<br>Relative Growth: %{y:.2f}%',
))

fig.update_layout(
    title='Water Transport Emissions Share Growth (1995 Baseline = 100%)',
    xaxis_title='Year',
    yaxis_title='Relative Increase Since 1995 (%)',
    legend=dict(x=0.5, xanchor='center', orientation='h'),
    hovermode='x unified'
)

fig.show()

In [29]:
# Plot emission (ppm) per million dollars due to water transport per year
emission_per_million_df = water_transport_df.iloc[:1]

emission_per_million_df = emission_per_million_df.melt(
    var_name='Year',
    value_name='emission_per_million'
)
emission_per_million_df['Year'] = emission_per_million_df['Year'].astype(int)
alt.Chart(emission_per_million_df).mark_line(point=True).encode(
    x=alt.X('Year:O', title='Year', axis=alt.Axis(labelAngle=0)),
    y=alt.Y('emission_per_million:Q', title='CO₂ Emissions per $1M Output'),
    tooltip=['Year', 'emission_per_million']
).properties(
    title='Water Transport CO₂ emission_per_million (1995–2018)',
    width=600,
    height=400
).interactive()

alt.Chart(yearly_sea_levels).mark_line(point=True).encode(
    x=alt.X('Year:O', title='Year'),
    y=alt.Y('AvgSeaLevel:Q', title='Average Sea Level (mm)'),
    tooltip=['Year', 'AvgSeaLevel']
).properties(
    title='Average Global Sea Level Change by Year',
    width=600,
    height=400
).interactive()

alt.Chart(...)

In [30]:
import altair as alt

# Line + area for emissions per $1M output (green)
emission_chart = alt.Chart(emission_per_million_df).mark_area(
    line={'color': 'green'},
    color='lightgreen',
    interpolate='monotone'
).encode(
    x=alt.X('Year:O', title='Year'),
    y=alt.Y('emission_per_million:Q', title='CO₂ Emissions per $1M Output'),
    tooltip=['Year', 'emission_per_million']
).properties(
    title='Water Transport CO₂ Emissions per $1M Output (1995–2018)',
)

# Line + area for sea levels (blue)
sea_level_chart = alt.Chart(yearly_sea_levels).mark_area(
    line={'color': 'blue'},
    color='lightblue',
    interpolate='monotone'
).encode(
    x=alt.X('Year:O', title='Year'),
    y=alt.Y('AvgSeaLevel:Q', title='Average Sea Level (mm)'),
    tooltip=['Year', 'AvgSeaLevel']
).properties(
    title='Average Global Sea Level Change by Year',
)

# Combine side-by-side
combined_chart = alt.hconcat(emission_chart, sea_level_chart)
combined_chart

alt.HConcatChart(...)

In [34]:
latest_emission = industry_df[industry_df['Unit'] == 'Millions of Metric tons of CO2'][['Industry', '1995', '2018']]

In [35]:
latest_emission = latest_emission.groupby('Industry').sum().reset_index()

In [36]:
latest_emission.sort_values('2018')

                                             Industry      1995       2018
1   Activities of households as employers; undiffe...     0.000      0.000
29                          Other transport equipment    12.049     14.671
35  Publishing, audiovisual and broadcasting activ...    23.269     21.842
5                  Arts, entertainment and recreation    18.712     23.649
25                  Mining support service activities    13.696     29.067
12                               Electrical equipment    37.411     29.896
41  Water supply; sewerage, waste management and r...    23.929     32.654
44                 Wood and products of wood and cork    39.478     32.768
28                           Other service activities    26.765     35.090
19                  IT and other information services    19.115     39.320
16                            Fishing and aquaculture    35.072     41.464
38                                 Telecommunications    33.662     45.638
9           Computer, electronic and optical products    59.200     50.540
26         Motor vehicles, trailers and semi-trailers    47.062     52.728
0                      Accomodation and food services    53.874     57.180
14                          Fabricated metal products    49.189     59.303
21                     Machinery and equipment n.e.c.    70.759     60.881
32                      Postal and courier activities    32.818     63.562
39   Textiles, textile products, leather and footwear   135.413     70.549
18            Human health and social work activities    67.158     89.574
40  Warehousing and support activities for transpo...    37.087    121.659
33  Professional, scientific and technical activities    76.102    123.601
15                 Financial and insurance activities    91.656    124.843
36                             Real estate activities   100.517    140.402
30                        Paper products and printing   210.125    141.747
11                                          Education    80.891    144.885
2                 Administrative and support services    79.870    173.357
24  Mining and quarrying, non-energy producing pro...    85.146    184.891
31  Pharmaceuticals, medicinal chemical and botani...   132.420    210.270
17               Food products, beverages and tobacco   267.993    272.100
34  Public administration and defence; compulsory ...   235.918    314.342
22  Manufacturing nec; repair and installation of ...   167.476    332.175
43  Wholesale and retail trade; repair of motor ve...   284.352    371.137
37                       Rubber and plastics products   233.484    421.584
10                                       Construction   228.742    467.522
3                      Agriculture, hunting, forestry   436.181    492.114
23    Mining and quarrying, energy producing products   361.052    591.425
7               Chemicals and pharmaceutical products   523.481    706.827
8                 Coke and refined petroleum products   729.301    769.383
42                                    Water transport   497.769    841.436
4                                       Air transport   554.145    953.339
20         Land transport and transport via pipelines   652.836   1068.843
27                Other non-metallic mineral products   671.963   1127.144
6                                        Basic metals  1524.871   3360.336
13  Electricity, gas, steam and air conditioning s...  6860.231  11950.073

In [37]:
import pandas as pd
import plotly.graph_objects as go

# Clean and convert emissions
latest_emission['2018'] = latest_emission['2018'].astype(float)

# Get top 5 emitters
top_emitters = latest_emission.sort_values('2018', ascending=False).head(5).copy()

# Add Water Transport row manually if not in top 5
water_row = latest_emission[latest_emission['Industry'].str.lower().str.contains('water transport')]

if not water_row.empty and not water_row['Industry'].iloc[0] in top_emitters['Industry'].values:
    top_emitters = pd.concat([top_emitters, water_row])

# Sort for clean plotting
top_emitters = top_emitters.sort_values('2018', ascending=True)

# Highlight water transport
colors = ['steelblue' if 'water transport' in ind.lower() else 'lightgray' for ind in top_emitters['Industry']]

# Create bar chart
fig = go.Figure(go.Bar(
    x=top_emitters['2018'],
    y=top_emitters['Industry'],
    orientation='h',
    marker_color=colors,
    hovertemplate='%{y}<br>Emissions: %{x:.2f} MtCO₂'
))

fig.update_layout(
    title='Top CO₂ Emitting Industries in 2018 (with Water Transport)',
    xaxis_title='CO₂ Emissions (Million Metric Tons)',
    yaxis_title='Industry',
    width=700,
    height=400
)

fig.show()

In [38]:
latest_emission

                                             Industry      1995       2018
0                      Accomodation and food services    53.874     57.180
1   Activities of households as employers; undiffe...     0.000      0.000
2                 Administrative and support services    79.870    173.357
3                      Agriculture, hunting, forestry   436.181    492.114
4                                       Air transport   554.145    953.339
5                  Arts, entertainment and recreation    18.712     23.649
6                                        Basic metals  1524.871   3360.336
7               Chemicals and pharmaceutical products   523.481    706.827
8                 Coke and refined petroleum products   729.301    769.383
9           Computer, electronic and optical products    59.200     50.540
10                                       Construction   228.742    467.522
11                                          Education    80.891    144.885
12                               Electrical equipment    37.411     29.896
13  Electricity, gas, steam and air conditioning s...  6860.231  11950.073
14                          Fabricated metal products    49.189     59.303
15                 Financial and insurance activities    91.656    124.843
16                            Fishing and aquaculture    35.072     41.464
17               Food products, beverages and tobacco   267.993    272.100
18            Human health and social work activities    67.158     89.574
19                  IT and other information services    19.115     39.320
20         Land transport and transport via pipelines   652.836   1068.843
21                     Machinery and equipment n.e.c.    70.759     60.881
22  Manufacturing nec; repair and installation of ...   167.476    332.175
23    Mining and quarrying, energy producing products   361.052    591.425
24  Mining and quarrying, non-energy producing pro...    85.146    184.891
25                  Mining support service activities    13.696     29.067
26         Motor vehicles, trailers and semi-trailers    47.062     52.728
27                Other non-metallic mineral products   671.963   1127.144
28                           Other service activities    26.765     35.090
29                          Other transport equipment    12.049     14.671
30                        Paper products and printing   210.125    141.747
31  Pharmaceuticals, medicinal chemical and botani...   132.420    210.270
32                      Postal and courier activities    32.818     63.562
33  Professional, scientific and technical activities    76.102    123.601
34  Public administration and defence; compulsory ...   235.918    314.342
35  Publishing, audiovisual and broadcasting activ...    23.269     21.842
36                             Real estate activities   100.517    140.402
37                       Rubber and plastics products   233.484    421.584
38                                 Telecommunications    33.662     45.638
39   Textiles, textile products, leather and footwear   135.413     70.549
40  Warehousing and support activities for transpo...    37.087    121.659
41  Water supply; sewerage, waste management and r...    23.929     32.654
42                                    Water transport   497.769    841.436
43  Wholesale and retail trade; repair of motor ve...   284.352    371.137
44                 Wood and products of wood and cork    39.478     32.768

In [39]:
# Ensure emissions are float
latest_emission['1995'] = latest_emission['1995'].astype(float)
latest_emission['2018'] = latest_emission['2018'].astype(float)

# Get top industries for both years (or just all of them)
df_1995 = latest_emission[['Industry', '1995']].copy()
df_1995.columns = ['Industry', 'Emissions']
df_1995['Year'] = 1995

df_2018 = latest_emission[['Industry', '2018']].copy()
df_2018.columns = ['Industry', 'Emissions']
df_2018['Year'] = 2018

In [40]:
# Tag water transport to color it differently
def tag_category(industry):
    return 'Water Transport' if 'water transport' in industry.lower() else 'Other'

df_1995['Highlight'] = df_1995['Industry'].apply(tag_category)
df_2018['Highlight'] = df_2018['Industry'].apply(tag_category)

In [41]:
from plotly.subplots import make_subplots
import plotly.graph_objects as go

# Make pie charts clean: show hover only, no visual text
fig = make_subplots(rows=1, cols=2, specs=[[{'type': 'domain'}, {'type': 'domain'}]],
                    subplot_titles=['1995', '2018'])

# Pie for 1995
fig.add_trace(go.Pie(
    labels=df_1995['Industry'],
    values=df_1995['Emissions'],
    marker_colors=[
        'steelblue' if h == 'Water Transport' else 'lightgray'
        for h in df_1995['Highlight']
    ],
    textinfo='none',  # 🔥 hide all labels
    hovertemplate='%{label}: %{percent}',
    name='1995'
), row=1, col=1)

# Pie for 2018
fig.add_trace(go.Pie(
    labels=df_2018['Industry'],
    values=df_2018['Emissions'],
    marker_colors=[
        'steelblue' if h == 'Water Transport' else 'lightgray'
        for h in df_2018['Highlight']
    ],
    textinfo='none',
    hovertemplate='%{label}: %{percent}',
    name='2018'
), row=1, col=2)

# Layout
fig.update_layout(
    title_text='CO₂ Emissions by Industry (1995 vs 2018)',
    width=900,
    height=500,
    showlegend=False
)

# Add floating annotation for Water Transport in 1995
fig.add_annotation(
    x=0.07, y=0.4,
    text=f"Water Transport: 3.13%",
    showarrow=True,
    font=dict(size=13, color='steelblue'),
    bgcolor='white',
    opacity=0.9
)
# Add floating annotation for Water Transport in 1995
fig.add_annotation(
    x=0.6, y=0.5,
    text=f"Water Transport: 3.2%",
    showarrow=True,
    font=dict(size=13, color='steelblue'),
    bgcolor='white',
    opacity=0.9
)
fig.show()